# Generated by Django 5.2.3 on 2025-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdocument',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerdocument',
            name='verified_by',
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='FarmerAnalytics',
        ),
        migrations.DeleteModel(
            name='FarmerDocument',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
